name: Lint Python Code

on:
  pull_request:
    branches:
      - main  # main ブランチに対する PR のとき実行

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Python のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint チェック (flake8)
        id: lint
        run: |
          output=$(flake8 . --count --show-source --statistics || true)
          echo "$output" > flake8_report.txt
          echo "::set-output name=lint_result::$output"

      - name: エラーがある場合コメントする
        if: steps.lint.outputs.lint_result != ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            **Lint エラーが検出されました** 🛑
            ```
            ${{ steps.lint.outputs.lint_result }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
